os: osx
language: generic
osx_image: xcode12.2
before_script:
  - pip install six
  - brew update
  - brew install --HEAD libimobiledevice
  - brew install ideviceinstaller
  - brew install ios-deploy
  - git clone https://github.com/flutter/flutter.git -n
  - cd flutter
  - git checkout -b working db6e2d8aa5bb9a0bd3e75fc7470268b5a56fd0b0
  - cd ..
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter -v build ios --no-codesign

cache:
  directories:
    - $HOME/.pub-cache
   